### ISSUE TITLE
Dutch Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-nl#1]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide to understand how to translate various technical and Gatsby-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Community

* [x] community/code-of-conduct @joranquinten #4 

### Tutorial

* [ ] tutorial/index @joranquinten #5 
* [ ] tutorial/part-zero @joranquinten #6
* [ ] tutorial/part-one @joranquinten #7 
* [ ] tutorial/part-two
* [ ] tutorial/part-three
* [ ] tutorial/part-four
* [ ] tutorial/part-five
* [ ] tutorial/part-six
* [ ] tutorial/part-seven
* [ ] tutorial/part-eight
    

### Docs

* [ ] docs/index
* [ ] docs/quick-start
* [ ] docs/glossary
* [ ] docs/gatsby-cli
    
#### Recipes

* [ ] docs/recipes
* [ ] docs/recipes/pages-layouts
* [ ] docs/recipes/styling-css
* [ ] docs/recipes/working-with-starters
* [ ] docs/recipes/working-with-themes
* [ ] docs/recipes/sourcing-data
* [ ] docs/recipes/querying-data
* [ ] docs/recipes/working-with-images
* [ ] docs/recipes/transforming-data
* [ ] docs/recipes/deploying-your-site

#### API Reference

* [ ] docs/api-reference
* [ ] docs/theme-api
* [ ] docs/gatsby-link
* [ ] docs/gatsby-image
* [ ] docs/gatsby-config
* [ ] docs/browser-apis
* [ ] docs/ssr-apis
* [ ] docs/api-files
* [ ] docs/api-files-gatsby-config
* [ ] docs/api-files-gatsby-browser
* [ ] docs/api-files-gatsby-node
* [ ] docs/api-files-gatsby-ssr
* [ ] docs/actions
* [ ] docs/graphql-api
* [ ] docs/node-apis
* [ ] docs/node-api-helpers
* [ ] docs/node-model
* [ ] docs/node-interface
* [ ] docs/schema-customization
* [ ] docs/api-specification

**Comment by erhankaradeniz** [comment]
docs/quick-start

**Comment by chiched** [comment]
Hi, I'd like to contribute. Can I start with translating:
docs/index ?

**Comment by MichaelDeBoey** [comment]
@chiched Go ahead! 🙂

**Comment by chiched** [comment]
Thanks:-)

**Comment by jaspervermeulen** [comment]
Hi, I'd like to contribute. Can I start with docs/recipes/pages-layouts ?

**Comment by chiched** [comment]
@jaspervermeulen Unfortunately, PR aren't been reviewed so I believe you would be wasting your time. I've translated a few pages back in March and still haven't heard back since...

**Comment by jaspervermeulen** [comment]
@chiched I've seen that you translated a few pages! Too bad they don't review them... Just wanted to see if I could help 😄

**Comment by chiched** [comment]
@jaspervermeulen Same as me :-)

**Comment by musti-91** [comment]
Ik wil ook meedoen!

**Comment by Kris-MultiSafepay** [comment]
I advise starting with translating the glossary. Through a controlled language (consistently using the same Dutch translations or choosing not to translate) ambiguity and complexity can be reduced. If the project will be picked up in the future I'd be happy to pitch in.
